### ISSUE TITLE
File allows unprotected direct access

### ISSUE THREAD

**Issue by mchurchward** [EEXCESS/moodle-atto_eexcesseditor#2]
I'm concerned about the file "/lib/editor/atto/plugins/eexcesseditor/savescreen.php". It creates output without checking for any logins or  capabilities. I could access it direct, and it spit out the error:

`{"error":"Cannot read file. Either the file does not exist or there is a permission problem.","stacktrace":"* line 1899 of \/lib\/filestorage\/file_storage.php: file_exception thrown\n* line 1456 of \/lib\/filestorage\/file_storage.php: call to file_storage->add_file_to_pool()\n* line 47 of \/lib\/editor\/atto\/plugins\/eexcesseditor\/savescreen.php: call to file_storage->create_file_from_pathname()\n","debuginfo":"[dirroot]\/lib\/editor\/atto\/plugins\/eexcesseditor\/pix\/screenshots\/574de012ed04d_file.png\nError code: storedfilecannotread","reproductionlink":"http:\/\/localhost\/moodlehq.git\/"}
`

I think you need to add login and capability checking, as well as a 
`defined('MOODLE_INTERNAL') || die();`
line

**Comment by megamuf** [comment]
Hello Mike,
Login and capability checking added. But I have a problem if I add the line "defined('MOODLE_INTERNAL') || die()" I can not add a screenshot it is necessary to add this line?

**Comment by mchurchward** [comment]
Hi -
If 'savescreen.php' is being called as a direct script (from the URL, for example), then you shouldn't have the "defined('MOODLE_INTERNAL') || die()". You need it if its being included as part of a main script.
If it is a main script, then the access security checks must be present for sure.

**Comment by megamuf** [comment]
Thank You Mike.

**Comment by mchurchward** [comment]
Hi. I looked at the new release. The file can still be directly accessed an the error above still gets displayed. I wonder if the script could detect if the file doesn't exist, and exit gracefully? I think the problem is that there is no valid 'imgdata" passed into the script, so that the file named in $tmppath doesn't really exist. Maybe "optional_param" should be "required_param"? Or check if $data is "false" and exit?
Just a suggestion.
